name: flemis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.3.9"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  camera: ^0.10.0+1
  cpfcnpj:
    git:
      url: https://github.com/erickhaendel/dart-cpfcnpj.git
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.0.1
  device_preview: ^1.1.0
  encrypt: ^5.0.1
  firebase_analytics: ^10.0.2
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_staggered_animations: ^1.1.1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  idb_shim: ^2.0.1+1
  image: ^3.2.2
  intl: ^0.17.0
  js: ^0.6.4
  json_dynamic_widget: ^5.1.2+3
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.0
  new_version: ^0.3.1
  package_info_plus: ^1.4.3
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  provider: ^6.0.3
  qlevar_router: ^1.6.2
  socket_io_client: ^2.0.0-beta.3-nullsafety.0
  sqflite: ^2.0.2+1
  stories_editor: ^0.2.2
  video_player: ^2.4.7

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: ""

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/fernando.jpg
    - assets/avatar.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
