// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmIsHbi9WVckTPQsZKvGI6MLcDQln7ZU',
    appId: '1:201376969510:web:7e828450056d8f6b3c07e7',
    messagingSenderId: '201376969510',
    projectId: 'flemis-80738',
    authDomain: 'flemis-80738.firebaseapp.com',
    storageBucket: 'flemis-80738.appspot.com',
    measurementId: 'G-TBWCF39YRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQf1bqw2knMy8eV7ZkucnT_1l8aZNeyc0',
    appId: '1:201376969510:android:e37c33230fffb1a23c07e7',
    messagingSenderId: '201376969510',
    projectId: 'flemis-80738',
    storageBucket: 'flemis-80738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5jlTQc1zKSFMMqcAN9SVwc72NztIXrQ',
    appId: '1:201376969510:ios:fce4dd052d46ae8c3c07e7',
    messagingSenderId: '201376969510',
    projectId: 'flemis-80738',
    storageBucket: 'flemis-80738.appspot.com',
    iosClientId: '201376969510-fgt91d2n25fap8fg5el7ssk65cvpvrb8.apps.googleusercontent.com',
    iosBundleId: 'com.fernandosini.flemis',
  );
}
